# Generated by Django 2.1.2 on 2018-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='year',
            field=models.IntegerField(verbose_name=4),
        ),
        migrations.AlterField(
            model_name='vehiclemsrpmodel',
            name='year',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
